### ISSUE TITLE
KAOS Retrieval TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by loljoho** [loljoho/TriviaTime#19]
Seems to be tied to 8eb9c91fe1a8ccc4bedca3bd2210ccaafc322b67 and #14 merge

```
ERROR 2019-03-21T23:37:27 Uncaught exception in scheduled function:
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/supybot/schedule.py", line 141, in run
    f(*args, **kwargs)
  File "/home/ec2-user/limnoria/plugins/TriviaTime/plugin.py", line 524, in nextQuestion
    retrievedQuestion = self.retrieveQuestion(True)
  File "/home/ec2-user/limnoria/plugins/TriviaTime/plugin.py", line 593, in retrieveQuestion
    rawQuestion = rawData['question']
TypeError: 'NoneType' object is not subscriptable
ERROR 2019-03-21T23:37:27 Exception id: 0x155d7
```

Works just fine on `develop` a715902c640e0218a7b9b4d69cf2e996b2052c2b

**Comment by loljoho** [comment]
Potentially due to https://github.com/loljoho/TriviaTime/commit/8eb9c91fe1a8ccc4bedca3bd2210ccaafc322b67#diff-66c71ea3faaa52c277917c951aa67921R916 ?

Running local bot on testing channel 24/7 to see if I can replicate.

**Comment by loljoho** [comment]
Set default value of KAOS frequency to `20`
